services:
    imatic_config.manager.config_manager:
        class: Imatic\Bundle\ConfigBundle\Manager\ConfigManager
        arguments: [@doctrine.orm.entity_manager, @imatic_config.manager.value_transformer]

    imatic_config.manager.value_transformer:
        class: Imatic\Bundle\ConfigBundle\Manager\ValueTransformer
        arguments: [@form.factory]