services:
    imatic_config.config_manager:
        class: Imatic\Bundle\ConfigBundle\Config\ConfigManager
        arguments: [@doctrine.orm.entity_manager, @imatic_config.value_transformer]

    imatic_config.reader:
        alias: imatic_config.config_manager

    imatic_config.value_transformer:
        class: Imatic\Bundle\ConfigBundle\Config\ValueTransformer
        arguments: [@form.factory]
        public: false